// Migration 107: زرعُ مكتبة بروتوكولات العلاج الطبيعي — **مسوّداتٌ لمراجعة المشرف العام** (§4.cj، المرحلةُ ٢ب، ٢٠٢٦-١٠-٠٧).
//
// أربعةٌ وأربعون بروتوكولاً بالفئة العمرية، لكلٍّ أجهزتُه من الخمسةَ عشر بدرجة دليل («موصى به / اختياري / غير موصى به») ومراجعُه
// العالمية (NICE · JOSPT/APTA · AAOS · OARSI · ACR · EULAR · AHA · Cochrane …). **كلُّها `draft`** — لا يُطبَّق شيءٌ منها قبل أن
// يعتمده سليمٌ أو المسؤول (§4.cj)، وتعديلُها من الشاشة.
//
// • **`ON CONFLICT (code) DO NOTHING`** — بروتوكولٌ بالرمز نفسِه (أضافه أحدٌ يدوياً) لا يُمَسّ، وأجهزتُه لا تُزرَع: الأجهزةُ تُدرَج
//   للصفّ المُدرَج الآن وحده (`WITH p AS (INSERT … RETURNING id)`).
// • **وجهازٌ غائبٌ من جدول `devices`** يُتخطّى بلا خطأ (`JOIN devices ON code`) — الرموزُ من قائمة الخمسةَ عشر نفسِها.
// • **والمراجعُ بلا رابطٍ حين لا يُتيقَّن منه** — عنوانٌ وجهةٌ وسنة يكفيان للبحث، ورابطٌ خاطئ أسوأ من غيابه.
// • والنصُّ عربيٌّ بالمصطلح الإنكليزيّ بين قوسين (قرارُ المالك). ولا مفتاحَ إلى `patients`.

type Ev = "recommended" | "optional" | "not_recommended";
type DevLine = [code: string, evidence: Ev, parameters?: string | null, minutes?: number | null, note?: string | null];
interface Ref { title: string; org: string; year: number; url?: string }
interface Seed {
  code: string; titleAr: string; titleEn: string;
  category: "spine" | "upper_limb" | "lower_limb" | "neurological" | "post_surgical" | "amputation" | "rheumatologic" | "other";
  ageGroup: "pediatric" | "adult" | "geriatric" | "all";
  summary: string; goals: string; assessment: string; exercises: string; contraindications: string; precautions: string;
  spw: number; weeks: number; minutes: number; refs: Ref[]; devices: DevLine[];
}

// ── المراجع ───────────────────────────────────────────────────────────────────
const R = {
  niceLbp: { title: "Low back pain and sciatica in over 16s: assessment and management (NG59)", org: "NICE", year: 2016, url: "https://www.nice.org.uk/guidance/ng59" },
  josptLbp: { title: "Interventions for the Management of Acute and Chronic Low Back Pain: Revision 2021", org: "JOSPT / APTA Orthopaedics", year: 2021, url: "https://doi.org/10.2519/jospt.2021.0304" },
  nassStenosis: { title: "Diagnosis and Treatment of Degenerative Lumbar Spinal Stenosis — Evidence-Based Clinical Guideline", org: "NASS", year: 2011 },
  josptNeck: { title: "Neck Pain: Revision 2017 — Clinical Practice Guidelines", org: "JOSPT / APTA Orthopaedics", year: 2017, url: "https://doi.org/10.2519/jospt.2017.0302" },
  sosort: { title: "2016 SOSORT guidelines: orthopaedic and rehabilitation treatment of idiopathic scoliosis during growth", org: "SOSORT", year: 2018 },
  subacromial: { title: "Guideline for diagnosis and treatment of subacromial pain syndrome", org: "Dutch Orthopaedic Association (Acta Orthopaedica)", year: 2014 },
  ismst: { title: "ISMST consensus on indications for extracorporeal shockwave therapy", org: "ISMST", year: 2016 },
  josptCapsulitis: { title: "Shoulder Pain and Mobility Deficits: Adhesive Capsulitis — Clinical Practice Guidelines", org: "JOSPT / APTA Orthopaedics", year: 2013, url: "https://doi.org/10.2519/jospt.2013.0302" },
  josptElbow: { title: "Lateral Elbow Pain and Muscle Function Impairments — Clinical Practice Guidelines", org: "JOSPT / APTA Orthopaedics", year: 2022 },
  josptCts: { title: "Hand Pain and Sensory Deficits: Carpal Tunnel Syndrome — Clinical Practice Guidelines", org: "JOSPT / APTA Hand & Upper Extremity", year: 2019, url: "https://doi.org/10.2519/jospt.2019.0301" },
  aaosCts: { title: "Management of Carpal Tunnel Syndrome — Evidence-Based Clinical Practice Guideline", org: "AAOS", year: 2016 },
  eularHand: { title: "2018 update of the EULAR recommendations for the management of hand osteoarthritis", org: "EULAR", year: 2019 },
  niceOa: { title: "Osteoarthritis in over 16s: diagnosis and management (NG226)", org: "NICE", year: 2022, url: "https://www.nice.org.uk/guidance/ng226" },
  acrOa: { title: "2019 ACR/Arthritis Foundation Guideline for the Management of Osteoarthritis of the Hand, Hip, and Knee", org: "ACR", year: 2020, url: "https://doi.org/10.1002/art.41142" },
  oarsi: { title: "OARSI guidelines for the non-surgical management of knee, hip, and polyarticular osteoarthritis", org: "OARSI", year: 2019, url: "https://doi.org/10.1016/j.joca.2019.06.011" },
  josptHipOa: { title: "Hip Pain and Mobility Deficits — Hip Osteoarthritis: Revision 2017", org: "JOSPT / APTA Orthopaedics", year: 2017, url: "https://doi.org/10.2519/jospt.2017.0301" },
  josptPfp: { title: "Patellofemoral Pain — Clinical Practice Guidelines", org: "JOSPT / APTA Orthopaedics", year: 2019, url: "https://doi.org/10.2519/jospt.2019.0302" },
  josptAchilles: { title: "Achilles Pain, Stiffness, and Muscle Power Deficits: Midportion Achilles Tendinopathy Revision 2018", org: "JOSPT / APTA Orthopaedics", year: 2018, url: "https://doi.org/10.2519/jospt.2018.0302" },
  josptHeel: { title: "Heel Pain — Plantar Fasciitis: Revision 2023", org: "JOSPT / APTA Orthopaedics", year: 2023 },
  josptAnkle: { title: "Ankle Stability and Movement Coordination Impairments: Lateral Ankle Ligament Sprains Revision 2021", org: "JOSPT / APTA Orthopaedics", year: 2021, url: "https://doi.org/10.2519/jospt.2021.0302" },
  josptMeniscus: { title: "Knee Pain and Mobility Impairments: Meniscal and Articular Cartilage Lesions Revision 2018", org: "JOSPT / APTA Orthopaedics", year: 2018, url: "https://doi.org/10.2519/jospt.2018.0301" },
  aaosAcl: { title: "Management of Anterior Cruciate Ligament Injuries — Evidence-Based Clinical Practice Guideline", org: "AAOS", year: 2022 },
  ptTka: { title: "Physical Therapist Management of Total Knee Arthroplasty — Clinical Practice Guideline", org: "APTA (Physical Therapy)", year: 2020 },
  aaosTka: { title: "Surgical Management of Osteoarthritis of the Knee — Evidence-Based Clinical Practice Guideline", org: "AAOS", year: 2022 },
  aaosHip: { title: "Management of Osteoarthritis of the Hip — Evidence-Based Clinical Practice Guideline", org: "AAOS", year: 2023 },
  aaosRc: { title: "Management of Rotator Cuff Injuries — Evidence-Based Clinical Practice Guideline", org: "AAOS", year: 2019 },
  aaosDrf: { title: "Management of Distal Radius Fractures — Evidence-Based Clinical Practice Guideline", org: "AAOS", year: 2020 },
  ahaStroke: { title: "Guidelines for Adult Stroke Rehabilitation and Recovery", org: "AHA / ASA", year: 2016, url: "https://doi.org/10.1161/STR.0000000000000098" },
  niceStroke: { title: "Stroke rehabilitation in adults (NG236)", org: "NICE", year: 2023, url: "https://www.nice.org.uk/guidance/ng236" },
  cochraneGait: { title: "Electromechanical-assisted training for walking after stroke", org: "Cochrane Database of Systematic Reviews", year: 2020 },
  hornby: { title: "Clinical Practice Guideline to Improve Locomotor Function Following Chronic Stroke, Incomplete Spinal Cord Injury, and Brain Injury", org: "ANPT (Journal of Neurologic Physical Therapy)", year: 2020 },
  pd: { title: "European Physiotherapy Guideline for Parkinson's Disease", org: "KNGF / ParkinsonNet", year: 2014 },
  niceMs: { title: "Multiple sclerosis in adults: management (NG220)", org: "NICE", year: 2022, url: "https://www.nice.org.uk/guidance/ng220" },
  bells: { title: "Clinical Practice Guideline: Bell's Palsy", org: "AAO-HNS", year: 2013 },
  cp: { title: "State of the Evidence Traffic Lights 2019: Systematic Review of Interventions for Preventing and Treating Children with Cerebral Palsy", org: "Novak et al. (Current Neurology and Neuroscience Reports)", year: 2020 },
  cmt: { title: "Physical Therapy Management of Congenital Muscular Torticollis: A 2018 Evidence-Based Clinical Practice Guideline", org: "APTA Academy of Pediatric Physical Therapy", year: 2018 },
  vaLla: { title: "VA/DoD Clinical Practice Guideline for Rehabilitation of Individuals with Lower Limb Amputation", org: "VA / DoD", year: 2017 },
  vaUla: { title: "VA/DoD Clinical Practice Guideline for the Management of Upper Extremity Amputation Rehabilitation", org: "VA / DoD", year: 2014 },
  acrRa: { title: "2022 ACR Guideline for Exercise, Rehabilitation, Diet, and Additional Integrative Interventions for Rheumatoid Arthritis", org: "ACR", year: 2022 },
  eularPa: { title: "EULAR recommendations for physical activity in people with inflammatory arthritis and osteoarthritis", org: "EULAR", year: 2018 },
  asas: { title: "ASAS-EULAR recommendations for the management of axial spondyloarthritis: 2022 update", org: "ASAS / EULAR", year: 2023 },
  eularFm: { title: "EULAR revised recommendations for the management of fibromyalgia", org: "EULAR", year: 2017, url: "https://doi.org/10.1136/annrheumdis-2016-209724" },
  falls: { title: "World guidelines for falls prevention and management for older adults: a global initiative", org: "World Falls Guidelines Task Force (Age and Ageing)", year: 2022 },
  isl: { title: "The Diagnosis and Treatment of Peripheral Lymphedema: Consensus Document of the International Society of Lymphology", org: "ISL", year: 2020 },
  acrJia: { title: "2021 ACR Guideline for the Treatment of Juvenile Idiopathic Arthritis", org: "ACR", year: 2022 },
} satisfies Record<string, Ref>;

// ملاحظاتٌ متكرّرة
const DN = "للمرخَّص بالإبر الجافة وحده (علَمُ «الإبر الجافة»)";
const WEAK = "دليلٌ ضعيف أو متضارب — مساعدٌ لا بديلٌ عن التمارين";

// ── البروتوكولات ───────────────────────────────────────────────────────────────
export const SEED: Seed[] = [
  // ═══ العمود الفقري ═══
  {
    code: "lbp-acute-adult", titleAr: "ألم أسفل الظهر الحادّ وتحت الحادّ", titleEn: "Acute / Subacute Low Back Pain (non-specific)",
    category: "spine", ageGroup: "adult",
    summary: "ألمٌ أسفل الظهر أقلّ من ١٢ أسبوعاً بلا علامات خطر (Red flags). الأساسُ الطمأنةُ والبقاءُ نشيطاً والتمارين.",
    goals: "تخفيفُ الألم، العودةُ للنشاط والعمل، منعُ التحوّل إلى ألمٍ مزمن.",
    assessment: "فرزُ علامات الخطر (Red flags) والعوامل النفسية (Yellow flags — STarT Back)، مقياسُ الألم (NPRS)، الإعاقة (Oswestry ODI)، مدى الحركة.",
    exercises: "تثقيفٌ وطمأنة، المشي المتدرّج، تمارينُ الحركة والتحكّم الحركي (Motor control)، تقويةُ الجذع، برنامجٌ منزليٌّ يوميّ.",
    contraindications: "علاماتُ خطر: متلازمة ذيل الفرس (Cauda equina)، كسر، عدوى، ورم، عجزٌ عصبيٌّ متقدّم — إحالةٌ فورية للطبيب.",
    precautions: "تجنّبُ الراحة في الفراش، وتجنّبُ الاعتماد على الأجهزة السلبية وحدها.",
    spw: 2, weeks: 4, minutes: 45, refs: [R.josptLbp, R.niceLbp],
    devices: [
      ["exercise", "recommended", "تمارين حركة وتحكّم حركي وتقوية جذع متدرّجة", 30],
      ["hot_pack", "optional", "حرارة سطحية ١٥–٢٠ دقيقة قبل التمارين", 15, "حرارةٌ سطحية مفيدةٌ للحادّ قصيرَ المدى"],
      ["infrared", "optional", null, 10, "بديلُ الحرارة السطحية"],
      ["electro", "not_recommended", null, null, "TENS لا يُنصح به (NICE)"],
      ["ultrasound", "not_recommended", null, null, "لا يُنصح به (NICE)"],
      ["traction", "not_recommended", null, null, "الشدّ لا يُنصح به (NICE · JOSPT)"],
    ],
  },
  {
    code: "lbp-chronic-adult", titleAr: "ألم أسفل الظهر المزمن", titleEn: "Chronic Low Back Pain (non-specific)",
    category: "spine", ageGroup: "adult",
    summary: "ألمٌ أكثر من ١٢ أسبوعاً. التمارينُ العلاجية مع التثقيف بعلم الألم (Pain neuroscience education) هي الأساس.",
    goals: "تحسينُ الوظيفة والقدرة على العمل، خفضُ الإعاقة والخوف من الحركة (Kinesiophobia).",
    assessment: "Oswestry ODI، NPRS، مقياسُ الخوف والتجنّب (FABQ / TSK)، اختباراتُ التحمّل للجذع، فرزُ علامات الخطر.",
    exercises: "تمارينُ تقوية وتحمّل للجذع والأطراف، تحكّمٌ حركي، تمارينُ هوائية، Pilates أو Yoga، تعرّضٌ متدرّج (Graded activity)، برنامجٌ منزليّ.",
    contraindications: "علاماتُ الخطر (كما في الحادّ) — إحالة.",
    precautions: "تجنّبُ تعزيز الخوف من الحركة، والاعتمادُ على النشاط الذاتي لا على الجلسات السلبية.",
    spw: 2, weeks: 8, minutes: 50, refs: [R.josptLbp, R.niceLbp],
    devices: [
      ["exercise", "recommended", "تقوية وتحمّل وتحكّم حركي + هوائي", 35],
      ["needle", "optional", "نقاطٌ زنادية (Trigger points) في العضلات القطنية والألوية", 10, DN],
      ["hot_pack", "optional", null, 15, "مساعدٌ قبل التمارين"],
      ["electro", "not_recommended", null, null, "TENS لا يُنصح به (NICE)"],
      ["ultrasound", "not_recommended", null, null, "لا يُنصح به (NICE)"],
      ["traction", "not_recommended", null, null, "لا يُنصح به"],
      ["laser", "not_recommended", null, null, "لا دليلَ كافٍ"],
      ["megnatik", "not_recommended", null, null, "لا دليلَ كافٍ"],
    ],
  },
  {
    code: "lumbar-radiculopathy-adult", titleAr: "عِرق النَّسا والاعتلال الجذري القطني", titleEn: "Lumbar Radiculopathy / Sciatica",
    category: "spine", ageGroup: "adult",
    summary: "ألمٌ ينتشر إلى الساق من انضغاط جذرٍ عصبيّ (غالباً انزلاقٌ غضروفي). أغلبُ الحالات تتحسّن بالعلاج التحفّظي.",
    goals: "مركزةُ الألم (Centralization)، تخفيفُ الألم الساقيّ، استعادةُ الوظيفة.",
    assessment: "اختبارُ رفع الساق المستقيمة (SLR)، الفحصُ العصبي (القوة والحسّ والمنعكسات)، ODI، NPRS؛ عجزٌ عصبيٌّ متزايد ⟵ إحالة.",
    exercises: "تمارينٌ مفضّلةُ الاتجاه (Directional preference — McKenzie)، تحريكٌ عصبيّ (Neural mobilization)، تقويةُ الجذع، مشيٌ متدرّج.",
    contraindications: "متلازمةُ ذيل الفرس، ضعفٌ حركيٌّ متقدّم أو متزايد — إحالةٌ عاجلة.",
    precautions: "إيقافُ أيّ تمرينٍ يزيد انتشارَ الألم إلى الطرف (Peripheralization).",
    spw: 2, weeks: 6, minutes: 45, refs: [R.niceLbp, R.josptLbp],
    devices: [
      ["exercise", "recommended", "تمارينُ الاتجاه المفضّل وتحريكٌ عصبيّ وتقوية", 30],
      ["hot_pack", "optional", null, 15, null],
      ["traction", "not_recommended", null, null, "الشدّ القطني لا يُنصح به (NICE)"],
      ["electro", "not_recommended", null, null, "TENS لا يُنصح به (NICE)"],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "lumbar-stenosis-geriatric", titleAr: "تضيّق القناة الشوكية القطنية", titleEn: "Degenerative Lumbar Spinal Stenosis",
    category: "spine", ageGroup: "geriatric",
    summary: "عرجٌ عصبيّ (Neurogenic claudication) يزيد بالوقوف والمشي ويخفّ بالانحناء للأمام والجلوس.",
    goals: "زيادةُ مسافة المشي، تخفيفُ الألم، الحفاظُ على الاستقلالية ومنعُ السقوط.",
    assessment: "مسافةُ المشي حتى ظهور الأعراض، اختبارُ المشي ٦ دقائق (6MWT)، ODI، التوازن (Berg / TUG)، الفحصُ العصبي.",
    exercises: "تمارينُ الانثناء (Flexion-based)، دراجةٌ ثابتة، مشيٌ على السير مع دعم، تقويةُ الجذع والأطراف السفلية، تمارينُ التوازن.",
    contraindications: "عجزٌ عصبيٌّ متزايد أو أعراضُ ذيل الفرس — إحالة.",
    precautions: "تجنّبُ فرط البسط القطني (Extension) المؤلم، وانتباهٌ لخطر السقوط وأمراض القلب المرافقة.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.nassStenosis],
    devices: [
      ["exercise", "recommended", "انثناء + دراجة + توازن + تقوية", 35],
      ["hot_pack", "optional", null, 15, null],
      ["traction", "not_recommended", null, null, "لا دليلَ على فائدته"],
      ["electro", "optional", "TENS لتخفيف الألم قصيرَ المدى", 15, WEAK],
    ],
  },
  {
    code: "neck-pain-mechanical-adult", titleAr: "ألم الرقبة الميكانيكي", titleEn: "Mechanical Neck Pain (with mobility deficits)",
    category: "spine", ageGroup: "adult",
    summary: "ألمٌ رقبيّ مع نقصٍ في الحركة بلا أعراضٍ عصبية. العلاجُ اليدويّ مع التمارين هو الأفضل.",
    goals: "تخفيفُ الألم، استعادةُ مدى الحركة، تحسينُ الوضعية والتحمّل.",
    assessment: "Neck Disability Index (NDI)، NPRS، مدى حركة الرقبة، اختبارُ العضلات العميقة القابضة (Cranio-cervical flexion test).",
    exercises: "تحريكٌ يدويّ (Mobilization / Manipulation) للرقبة والظهر، تمارينُ العضلات العميقة القابضة، تقويةُ الكتف والظهر العلوي، تمارينُ الوضعية.",
    contraindications: "علاماتُ قصور الشريان الفقري، عدمُ ثبات الرقبة، كسر، ورم — إحالة.",
    precautions: "التحريكُ عالي السرعة (Manipulation) للمختصّ فقط وبعد فحص السلامة.",
    spw: 2, weeks: 6, minutes: 45, refs: [R.josptNeck],
    devices: [
      ["exercise", "recommended", "عضلات عميقة + تقوية كتف/ظهر علوي + وضعية", 30],
      ["needle", "optional", "نقاطٌ زنادية في العضلة شبه المنحرفة (Upper trapezius)", 10, DN],
      ["laser", "optional", "ليزرٌ منخفض الشدّة على النقاط المؤلمة", 10, WEAK],
      ["hot_pack", "optional", null, 15, null],
      ["electro", "optional", "TENS", 15, WEAK],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "cervical-radiculopathy-adult", titleAr: "الاعتلال الجذري العنقي", titleEn: "Cervical Radiculopathy (neck pain with radiating pain)",
    category: "spine", ageGroup: "adult",
    summary: "ألمٌ رقبيّ ينتشر إلى الذراع مع تنميلٍ أو ضعف من انضغاط جذرٍ عنقيّ.",
    goals: "تخفيفُ الألم الذراعي، مركزةُ الأعراض، استعادةُ القوة والوظيفة.",
    assessment: "عنقودُ Wainner (Spurling، Distraction، ULTT A، الدوران < ٦٠°)، الفحصُ العصبي، NDI، NPRS.",
    exercises: "تحريكٌ يدويّ، تمارينُ العضلات العميقة، تحريكٌ عصبيّ (Neural mobilization)، تقويةُ الكتف.",
    contraindications: "اعتلالُ النخاع العنقي (Myelopathy)، ضعفٌ متزايد — إحالة.",
    precautions: "إيقافُ أيّ وضعيةٍ تزيد الأعراضَ العصبية.",
    spw: 2, weeks: 6, minutes: 45, refs: [R.josptNeck],
    devices: [
      ["exercise", "recommended", null, 30],
      ["traction", "optional", "شدٌّ عنقيّ متقطّع (Intermittent mechanical traction) مع التمارين والعلاج اليدوي", 15, "JOSPT: يمكن استعماله مع غيره، لا وحده"],
      ["hot_pack", "optional", null, 15, null],
      ["electro", "optional", "TENS", 15, WEAK],
    ],
  },
  {
    code: "whiplash-adult", titleAr: "إصابة الرقبة الارتدادية", titleEn: "Whiplash-Associated Disorder (WAD)",
    category: "spine", ageGroup: "adult",
    summary: "ألمٌ رقبيّ بعد حادث تسارعٍ وتباطؤ (حادث سيارة). التثقيفُ والحركةُ المبكّرة أفضلُ من التجميد.",
    goals: "عودةٌ مبكّرة للنشاط، تخفيفُ الألم، منعُ التحوّل إلى مزمن.",
    assessment: "تصنيفُ Quebec (WAD I–III)، قواعدُ Canadian C-spine لاستبعاد الكسر، NDI، NPRS.",
    exercises: "تثقيفٌ وطمأنة، تمارينُ حركةٍ مبكّرة، تمارينُ العضلات العميقة، تمارينُ الإحساس الحركي (Proprioception) للرقبة.",
    contraindications: "كسرٌ أو عدمُ ثبات (WAD IV) — إحالة.",
    precautions: "تجنّبُ الطوق العنقي (Collar) لمدّةٍ طويلة.",
    spw: 2, weeks: 6, minutes: 45, refs: [R.josptNeck],
    devices: [
      ["exercise", "recommended", null, 30],
      ["hot_pack", "optional", null, 15, null],
      ["electro", "optional", "TENS", 15, WEAK],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "scoliosis-ais-pediatric", titleAr: "الجنف المجهول السبب عند المراهقين", titleEn: "Adolescent Idiopathic Scoliosis (AIS)",
    category: "spine", ageGroup: "pediatric",
    summary: "انحناءٌ جانبيٌّ ثلاثيّ الأبعاد أثناء النموّ. التمارينُ الخاصّة بالجنف (PSSE) مع الدعامة بحسب زاوية Cobb.",
    goals: "إيقافُ تقدّم الانحناء، تحسينُ الوضعية والمظهر والتنفّس، دعمُ الالتزام بالدعامة (Brace).",
    assessment: "زاويةُ Cobb من الأشعة، Risser للنضج العظمي، اختبارُ آدم مع Scoliometer، الصورُ الوضعية.",
    exercises: "تمارينُ خاصّة بالجنف (PSSE — Schroth / SEAS)، تصحيحٌ ذاتيّ ثلاثيّ الأبعاد، تنفّسٌ تصحيحيّ، تقويةُ الجذع.",
    contraindications: "الجنفُ الثانوي (عصبيّ، خِلقيّ) يحتاج تقييماً طبياً قبل البرنامج.",
    precautions: "متابعةُ زاوية Cobb مع الطبيب؛ الانحناءاتُ الكبيرة (> ٤٥°) للجرّاح.",
    spw: 2, weeks: 12, minutes: 60, refs: [R.sosort],
    devices: [
      ["exercise", "recommended", "PSSE (Schroth / SEAS) وبرنامجٌ منزليٌّ يوميّ", 50],
      ["electro", "not_recommended", null, null, "التحفيزُ الكهربائي السطحي لا يوقف التقدّم"],
    ],
  },

  // ═══ الطرف العلوي ═══
  {
    code: "subacromial-pain-adult", titleAr: "متلازمة ألم تحت الأخرم / اعتلال أوتار الكفة المدوّرة", titleEn: "Subacromial Pain Syndrome / Rotator Cuff Tendinopathy",
    category: "upper_limb", ageGroup: "adult",
    summary: "ألمٌ في الكتف مع رفع الذراع. التمارينُ العلاجية المتدرّجة هي العلاجُ الأوّل.",
    goals: "تخفيفُ الألم، استعادةُ القوة والتحكّم في لوح الكتف، العودةُ للعمل والرياضة.",
    assessment: "SPADI أو DASH، NPRS، مدى الحركة، قوةُ الكفة المدوّرة، اختباراتُ Hawkins و Neer و Painful arc.",
    exercises: "تقويةُ الكفة المدوّرة (Eccentric / Isometric ثم متدرّجة)، تثبيتُ لوح الكتف (Scapular stabilization)، تمطيطُ المحفظة الخلفية.",
    contraindications: "تمزّقٌ كاملٌ حادّ بعد إصابة مع ضعفٍ شديد — إحالةٌ للتقييم الجراحي.",
    precautions: "الألمُ أثناء التمرين مقبولٌ إن لم يتجاوز ٤/١٠ ويهدأ خلال ٢٤ ساعة.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.subacromial],
    devices: [
      ["exercise", "recommended", null, 35],
      ["shockwaves", "not_recommended", null, null, "بلا تكلّس لا فائدةَ ثابتة — انظر بروتوكول التكلّس"],
      ["ultrasound", "not_recommended", null, null, null],
      ["laser", "optional", null, 10, WEAK],
      ["needle", "optional", "نقاطٌ زنادية في Infraspinatus و Upper trapezius", 10, DN],
      ["hot_pack", "optional", null, 15, null],
    ],
  },
  {
    code: "calcific-shoulder-adult", titleAr: "التهاب أوتار الكتف التكلّسي", titleEn: "Calcific Tendinopathy of the Shoulder",
    category: "upper_limb", ageGroup: "adult",
    summary: "ترسّبُ كالسيوم في أوتار الكفة المدوّرة مع ألمٍ مزمن. الموجاتُ الصادمة من أقوى العلاجات التحفّظية.",
    goals: "تخفيفُ الألم، تقليلُ حجم التكلّس، استعادةُ الحركة.",
    assessment: "الأشعة (حجمُ التكلّس ونوعُه)، SPADI أو Constant score، NPRS، مدى الحركة.",
    exercises: "تمارينُ مدى الحركة ثم تقويةُ الكفة المدوّرة وتثبيتُ لوح الكتف.",
    contraindications: "للموجات الصادمة: الحمل، اضطراباتُ التخثّر ومضادّات التخثّر، عدوى أو ورمٌ موضعيّ، صفائحُ النموّ المفتوحة.",
    precautions: "ألمٌ مؤقّت بعد جلسة الموجات الصادمة متوقَّع.",
    spw: 1, weeks: 5, minutes: 40, refs: [R.ismst, R.subacromial],
    devices: [
      ["shockwaves", "recommended", "موجاتٌ صادمة مركّزة (Focused ESWT) — جلسةٌ أسبوعياً ٣–٥ جلسات", 15, "التكلّسُ من أقوى دواعي الموجات الصادمة"],
      ["exercise", "recommended", null, 25],
      ["ultrasound", "optional", null, 10, WEAK],
    ],
  },
  {
    code: "frozen-shoulder-adult", titleAr: "الكتف المتجمّد", titleEn: "Adhesive Capsulitis (Frozen Shoulder)",
    category: "upper_limb", ageGroup: "adult",
    summary: "تيبّسٌ مؤلمٌ في الكتف بمراحل: مؤلمة، متجمّدة، ذوبان. الشدّةُ تُضبط بحسب حساسية النسيج.",
    goals: "تخفيفُ الألم، استعادةُ مدى الحركة تدريجياً، الحفاظُ على الوظيفة.",
    assessment: "مدى الحركة (خاصّةً الدوران الخارجي)، SPADI، NPRS، تحديدُ المرحلة وحساسية النسيج (Irritability).",
    exercises: "في المرحلة المؤلمة: حركةٌ لطيفة بلا ألمٍ زائد؛ لاحقاً: تحريكٌ مفصليّ (Joint mobilization)، تمطيطٌ متدرّج، تقوية.",
    contraindications: "كسرٌ أو خلعٌ غيرُ مشخّص.",
    precautions: "السكّريّ يطيل المدّة؛ الشدّةُ العالية في المرحلة المؤلمة تزيد الأعراض.",
    spw: 2, weeks: 12, minutes: 45, refs: [R.josptCapsulitis],
    devices: [
      ["exercise", "recommended", "تمطيطٌ متدرّج بحسب المرحلة", 30],
      ["hot_pack", "optional", "حرارةٌ قبل التمطيط", 15, "حرارةٌ قبل الحركة تفيد"],
      ["tecar", "optional", null, 15, "دليلٌ محدود"],
      ["ultrasound", "optional", "حرارةٌ عميقة قبل التمطيط", 8, WEAK],
      ["electro", "optional", "TENS للألم", 15, WEAK],
      ["cpm", "not_recommended", null, null, "لا دليلَ كافٍ للكتف المتجمّد"],
    ],
  },
  {
    code: "lateral-elbow-adult", titleAr: "مرفق التنس", titleEn: "Lateral Elbow Pain / Tendinopathy (Tennis Elbow)",
    category: "upper_limb", ageGroup: "adult",
    summary: "ألمٌ على اللقيمة الوحشية مع القبض. التمارينُ المتدرّجة للأوتار هي الأساس.",
    goals: "تخفيفُ الألم، استعادةُ قوة القبضة الخالية من الألم (Pain-free grip)، العودةُ للعمل.",
    assessment: "PRTEE، قوةُ القبضة بلا ألم، NPRS، اختباراتُ Cozen و Mill.",
    exercises: "تمارينُ متساويةُ القياس ثم لامركزية (Isometric ⟵ Eccentric) لباسطات الرسغ، تقويةُ الكتف والقبضة، تعديلُ النشاط.",
    contraindications: "اعتلالُ جذر C6 أو انضغاطُ العصب الكعبري — يُفرَّق قبل البدء.",
    precautions: "حزامُ الساعد (Counterforce brace) مساعدٌ قصيرُ المدى.",
    spw: 2, weeks: 8, minutes: 40, refs: [R.josptElbow],
    devices: [
      ["exercise", "recommended", null, 25],
      ["shockwaves", "optional", "موجاتٌ صادمة شعاعية أو مركّزة، ٣–٥ جلسات", 10, "للمزمن الذي لم يستجب للتمارين"],
      ["laser", "optional", null, 10, WEAK],
      ["needle", "optional", "نقاطٌ زنادية في باسطات الرسغ", 10, DN],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "carpal-tunnel-adult", titleAr: "متلازمة النفق الرسغي", titleEn: "Carpal Tunnel Syndrome",
    category: "upper_limb", ageGroup: "adult",
    summary: "انضغاطُ العصب المتوسّط في الرسغ: تنميلٌ ليليّ في الأصابع الثلاثة الأولى. الخفيفُ والمتوسّط يُعالَج تحفّظياً.",
    goals: "تخفيفُ الأعراض الليلية، الحفاظُ على القوة والإحساس، تأخيرُ الجراحة أو تجنّبها.",
    assessment: "Boston CTS Questionnaire، اختباراتُ Phalen و Tinel، الحسّ والقوة (Thenar)، تخطيطُ الأعصاب إن لزم.",
    exercises: "جبيرةٌ ليلية محايدة (Night splint)، تمارينُ انزلاق العصب والأوتار (Nerve & tendon gliding)، تعديلُ الأنشطة.",
    contraindications: "ضمورُ عضلات الإبهام أو عجزٌ حسّيٌّ مستمرّ — إحالةٌ جراحية.",
    precautions: "تجنّبُ الضغط المباشر والحرارة الزائدة على الرسغ.",
    spw: 2, weeks: 6, minutes: 30, refs: [R.josptCts, R.aaosCts],
    devices: [
      ["exercise", "recommended", "انزلاقُ العصب والأوتار مع الجبيرة الليلية", 20],
      ["laser", "optional", null, 10, WEAK],
      ["ultrasound", "optional", "نبضيّ (Pulsed) على النفق الرسغي", 8, WEAK],
      ["megnatik", "not_recommended", null, null, "لا دليلَ كافٍ"],
      ["wax", "not_recommended", null, null, "الحرارةُ لا تفيد الانضغاط"],
    ],
  },
  {
    code: "hand-oa-geriatric", titleAr: "خشونة مفاصل اليد", titleEn: "Hand Osteoarthritis",
    category: "upper_limb", ageGroup: "geriatric",
    summary: "خشونةُ مفاصل الأصابع وقاعدة الإبهام. التثقيفُ والتمارين والجبائر والحرارة.",
    goals: "تخفيفُ الألم والتيبّس، الحفاظُ على قوة القبضة ووظيفة اليد.",
    assessment: "AUSCAN أو FIHOA، قوةُ القبضة والقرص (Pinch)، مدى الحركة، NPRS.",
    exercises: "تمارينُ مدى الحركة والتقوية لليد، حمايةُ المفاصل (Joint protection)، أدواتٌ مساعدة، جبيرةٌ لقاعدة الإبهام.",
    contraindications: "التهابٌ حادٌّ أو عدوى في المفصل.",
    precautions: "الحرارةُ بحذر مع ضعف الإحساس.",
    spw: 2, weeks: 6, minutes: 30, refs: [R.eularHand, R.acrOa],
    devices: [
      ["exercise", "recommended", null, 20],
      ["wax", "recommended", "شمعُ البارافين ١٥ دقيقة قبل التمارين", 15, "الحرارةُ موصى بها شرطياً (ACR)"],
      ["hot_pack", "optional", null, 15, null],
      ["laser", "optional", null, 10, WEAK],
      ["electro", "not_recommended", null, null, "TENS لا يُنصح به (ACR)"],
    ],
  },

  // ═══ الطرف السفلي ═══
  {
    code: "knee-oa-geriatric", titleAr: "خشونة الركبة", titleEn: "Knee Osteoarthritis",
    category: "lower_limb", ageGroup: "geriatric",
    summary: "التمارينُ وإنقاصُ الوزن والتثقيف هي العلاجُ الأساسيّ في كلّ الإرشادات.",
    goals: "تخفيفُ الألم، تقويةُ الفخذ، تحسينُ المشي والوظيفة، منعُ السقوط.",
    assessment: "KOOS أو WOMAC، NPRS، اختبارُ الجلوس والقيام ٣٠ ثانية، TUG، المشي ٤٠ متراً، قوةُ الفخذ.",
    exercises: "تقويةُ الرباعية والألوية، تمارينُ هوائية منخفضةُ الأثر (دراجة، مشي، ماء)، توازن، برنامجٌ منزليّ، إنقاصُ الوزن.",
    contraindications: "التهابٌ حادٌّ أو عدوى مفصلية، ألمٌ ليليّ غيرُ مفسَّر — إحالة.",
    precautions: "تعديلُ الشدّة بحسب الألم، وانتباهٌ لأمراض القلب.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.niceOa, R.acrOa, R.oarsi],
    devices: [
      ["exercise", "recommended", "تقوية + هوائي + توازن", 35],
      ["hot_pack", "optional", null, 15, "الحرارةُ موصى بها شرطياً (ACR)"],
      ["infrared", "optional", null, 10, null],
      ["laser", "optional", null, 10, WEAK],
      ["megnatik", "optional", null, 15, WEAK],
      ["tecar", "optional", null, 15, "دليلٌ محدود"],
      ["electro", "not_recommended", null, null, "TENS: توصيةٌ قوية ضدّه (ACR)"],
      ["ultrasound", "not_recommended", null, null, null],
      ["needle", "not_recommended", null, null, "NICE: لا يُقدَّم الوخزُ ولا الإبرُ الجافة للخشونة"],
    ],
  },
  {
    code: "hip-oa-geriatric", titleAr: "خشونة الورك", titleEn: "Hip Osteoarthritis",
    category: "lower_limb", ageGroup: "geriatric",
    summary: "ألمٌ في الأربية وتيبّسٌ ونقصُ دوران. التمارينُ والعلاجُ اليدويّ والتثقيف.",
    goals: "تخفيفُ الألم، تحسينُ مدى الحركة والمشي، الحفاظُ على الاستقلالية.",
    assessment: "HOOS أو WOMAC، مدى الحركة (الدوران الداخلي)، الجلوس والقيام ٣٠ ثانية، 6MWT، TUG.",
    exercises: "تحريكٌ يدويّ للورك، تقويةُ الألوية والفخذ، تمطيط، هوائيٌّ منخفضُ الأثر، توازن، استعمالُ العصا عند الحاجة.",
    contraindications: "النخرُ اللاوعائي (Avascular necrosis) أو كسرٌ غيرُ مشخّص — إحالة.",
    precautions: "تجنّبُ الحمل الزائد المؤلم.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.josptHipOa, R.niceOa, R.acrOa],
    devices: [
      ["exercise", "recommended", null, 35],
      ["hot_pack", "optional", null, 15, null],
      ["electro", "not_recommended", null, null, "TENS لا يُنصح به (ACR)"],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "patellofemoral-pain-adult", titleAr: "ألم الرضفة الفخذي", titleEn: "Patellofemoral Pain",
    category: "lower_limb", ageGroup: "adult",
    summary: "ألمٌ حول الرضفة يزيد بالقرفصاء والدرج والجلوس الطويل — شائعٌ عند الرياضيين والمراهقين.",
    goals: "تخفيفُ الألم، تقويةُ الورك والركبة، العودةُ للرياضة.",
    assessment: "Kujala (AKPS)، NPRS، القرفصاءُ على ساقٍ واحدة، قوةُ الألوية والرباعية.",
    exercises: "تقويةُ الورك (Abductors / External rotators) مع الركبة، تعديلُ الأحمال، Taping أو Orthoses قصيرةُ المدى.",
    contraindications: "انصبابٌ مفصليٌّ كبير أو عدمُ ثبات الرضفة بعد خلع — تقييمٌ آخر.",
    precautions: "تجنّبُ الأحمال المؤلمة في البداية.",
    spw: 2, weeks: 6, minutes: 45, refs: [R.josptPfp],
    devices: [
      ["exercise", "recommended", "ورك + ركبة", 35],
      ["electro", "not_recommended", null, null, "NMES/TENS لا يُنصح بهما (JOSPT)"],
      ["ultrasound", "not_recommended", null, null, null],
      ["laser", "not_recommended", null, null, null],
    ],
  },
  {
    code: "achilles-tendinopathy-adult", titleAr: "اعتلال وتر أخيل", titleEn: "Midportion Achilles Tendinopathy",
    category: "lower_limb", ageGroup: "adult",
    summary: "ألمٌ وتيبّسٌ صباحيّ في منتصف وتر أخيل. التحميلُ المتدرّج للوتر هو الأساس.",
    goals: "تخفيفُ الألم، استعادةُ قدرة الوتر على التحميل، العودةُ للجري.",
    assessment: "VISA-A، اختبارُ رفع الكعب المتكرّر، NPRS، الجسّ.",
    exercises: "تمارينُ التحميل المتدرّج (Eccentric — Alfredson، أو Heavy slow resistance)، ثم تمارينُ القفز والعودةُ للجري.",
    contraindications: "تمزّقٌ كامل (اختبارُ Thompson) — إحالة.",
    precautions: "الألمُ أثناء التمرين مقبولٌ حتى ٥/١٠ ويهدأ صباحَ اليوم التالي.",
    spw: 2, weeks: 12, minutes: 40, refs: [R.josptAchilles],
    devices: [
      ["exercise", "recommended", "تحميلٌ متدرّج للوتر", 25],
      ["laser", "optional", "ليزرٌ منخفضُ الشدّة", 10, "JOSPT: يمكن استعماله"],
      ["shockwaves", "optional", "موجاتٌ صادمة شعاعية ٣–٥ جلسات", 10, "للمزمن مع التمارين"],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "plantar-heel-pain-adult", titleAr: "التهاب اللفافة الأخمصية", titleEn: "Plantar Heel Pain / Plantar Fasciitis",
    category: "lower_limb", ageGroup: "adult",
    summary: "ألمٌ أسفل الكعب مع الخطوات الأولى صباحاً.",
    goals: "تخفيفُ ألم الصباح، العودةُ للمشي والعمل بلا ألم.",
    assessment: "FAAM أو FFI، NPRS لألم الخطوة الأولى، مدى حركة الكاحل (Dorsiflexion)، الجسّ.",
    exercises: "تمطيطُ اللفافة الأخمصية وعضلة الساق، تقويةُ القدم والساق، Taping، دعاماتُ القدم (Orthoses)، جبيرةٌ ليلية للمزمن.",
    contraindications: "كسرٌ إجهاديّ في عظم الكعب أو انضغاطٌ عصبيّ (Baxter) — يُفرَّق.",
    precautions: "للموجات الصادمة: الحمل، مضادّاتُ التخثّر، الأطفال (صفائحُ النموّ).",
    spw: 2, weeks: 6, minutes: 40, refs: [R.josptHeel],
    devices: [
      ["exercise", "recommended", "تمطيطُ اللفافة والساق + تقوية", 20],
      ["shockwaves", "recommended", "موجاتٌ صادمة (Radial أو Focused) ٣–٥ جلسات أسبوعية", 10, "JOSPT 2023: موصى بها"],
      ["laser", "optional", null, 10, null],
      ["needle", "optional", "نقاطٌ زنادية في عضلة الساق والقدم", 10, DN],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },
  {
    code: "ankle-sprain-adult", titleAr: "التواء الكاحل الوحشي", titleEn: "Lateral Ankle Sprain",
    category: "lower_limb", ageGroup: "adult",
    summary: "إصابةُ أربطة الكاحل الوحشية. الحمايةُ القصيرة ثم التحميلُ المبكّر وتمارينُ التوازن تمنع التكرار.",
    goals: "تخفيفُ التورّم والألم، استعادةُ الحركة والقوة والتوازن، منعُ عدم الثبات المزمن.",
    assessment: "قواعدُ أوتاوا (Ottawa) لاستبعاد الكسر، الدرجة، FAAM، اختبارُ Y-balance، مدى الحركة.",
    exercises: "في الحادّ: حماية (Brace)، رفع، تحميلٌ مبكّر؛ ثم مدى حركة، تقوية، توازنٌ وإحساسٌ حركيّ (Proprioception)، تدريبٌ وظيفيّ ورياضيّ.",
    contraindications: "كسرٌ بحسب قواعد أوتاوا — أشعّة أوّلاً.",
    precautions: "الدعامةُ في الرياضة لسنةٍ بعد الإصابة تقلّل التكرار.",
    spw: 2, weeks: 6, minutes: 40, refs: [R.josptAnkle],
    devices: [
      ["exercise", "recommended", "توازن + تقوية + وظيفيّ", 30],
      ["compression", "optional", "ضغطٌ متقطّع للتورّم في الطور الحادّ", 15, "للتورّم في الأيام الأولى"],
      ["laser", "optional", null, 10, WEAK],
      ["ultrasound", "not_recommended", null, null, "JOSPT: لا يُنصح به"],
      ["electro", "not_recommended", null, null, null],
    ],
  },
  {
    code: "knee-meniscal-adult", titleAr: "إصابات الغضروف الهلالي (تحفّظي أو بعد الاستئصال الجزئي)", titleEn: "Meniscal Lesions — Non-operative / Post-meniscectomy",
    category: "lower_limb", ageGroup: "adult",
    summary: "ألمٌ وانغلاقٌ أحياناً في الركبة. التمارينُ تعادل الجراحةَ في التمزّقات التنكّسية.",
    goals: "تخفيفُ الألم والانصباب، استعادةُ الحركة الكاملة وقوة الفخذ، العودةُ للنشاط.",
    assessment: "KOOS، IKDC، مدى الحركة، الانصباب (Stroke test)، قوةُ الرباعية.",
    exercises: "تمارينُ مدى الحركة، تقويةُ الرباعية والألوية، تحكّمٌ عصبيٌّ عضليّ (Neuromuscular)، تدريبٌ وظيفيّ متدرّج.",
    contraindications: "ركبةٌ مقفلة (Locked knee) لا تنفكّ — إحالةٌ جراحية.",
    precautions: "تحميلٌ متدرّج بحسب الانصباب والألم.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.josptMeniscus],
    devices: [
      ["exercise", "recommended", null, 35],
      ["electro", "recommended", "NMES للرباعية عند ضعفها", 15, "JOSPT: لتقوية الرباعية"],
      ["compression", "optional", null, 15, "للانصباب بعد الجراحة"],
      ["cpm", "not_recommended", null, null, null],
    ],
  },

  // ═══ ما بعد العمليات ═══
  {
    code: "acl-reconstruction-adult", titleAr: "ما بعد إعادة بناء الرباط الصليبي الأمامي", titleEn: "ACL Reconstruction Rehabilitation",
    category: "post_surgical", ageGroup: "adult",
    summary: "تأهيلٌ مرحليّ ٩–١٢ شهراً بمعايير لا بالزمن وحده، والعودةُ للرياضة باختباراتٍ موضوعية.",
    goals: "بسطٌ كامل مبكّراً، استعادةُ قوة الرباعية، التحكّمُ العصبي العضلي، عودةٌ آمنة للرياضة.",
    assessment: "مدى الحركة، الانصباب، قوةُ الرباعية (LSI)، اختباراتُ القفز (Hop tests)، IKDC، ACL-RSI.",
    exercises: "مرحلةٌ مبكّرة: بسطٌ كامل، تفعيلُ الرباعية، مشيٌ بلا عكّاز؛ ثم تقويةٌ مغلقة ومفتوحة السلسلة، توازن، جري، قفز، تدريبٌ رياضيّ.",
    contraindications: "علاماتُ عدوى أو جلطةٍ وريدية — إحالةٌ فورية.",
    precautions: "تمارينُ السلسلة المفتوحة بحسب نوع الطُّعم وتعليمات الجرّاح؛ لا عودةَ للرياضة قبل ٩ أشهر واجتياز المعايير.",
    spw: 3, weeks: 24, minutes: 60, refs: [R.aaosAcl],
    devices: [
      ["exercise", "recommended", "مرحليٌّ بالمعايير", 45],
      ["electro", "recommended", "NMES للرباعية في الأسابيع الأولى", 15, "يحسّن قوةَ الرباعية"],
      ["compression", "optional", "ضغطٌ وتبريد للتورّم", 15, null],
      ["cpm", "not_recommended", null, null, "لا فائدةَ ثابتة بعد الصليبي"],
    ],
  },
  {
    code: "tka-geriatric", titleAr: "ما بعد استبدال مفصل الركبة الكلّي", titleEn: "Total Knee Arthroplasty (TKA) Rehabilitation",
    category: "post_surgical", ageGroup: "geriatric",
    summary: "حركةٌ مبكّرة من يوم العملية، واستعادةُ البسط والانثناء وقوة الرباعية.",
    goals: "مدى حركة ٠–١١٠° على الأقلّ، مشيٌ مستقلّ، قوةُ الرباعية، صعودُ الدرج.",
    assessment: "مدى الحركة، TUG، الجلوس والقيام ٣٠ ثانية، 6MWT، KOOS-JR، الألم والتورّم.",
    exercises: "تمارينُ مدى الحركة والبسط، تقويةُ الرباعية والورك، تدريبُ المشي والدرج، توازن، برنامجٌ منزليّ.",
    contraindications: "علاماتُ عدوى الجرح أو جلطةٍ وريدية — إحالةٌ فورية.",
    precautions: "مراقبةُ الجرح والتورّم والألم؛ تعليماتُ الجرّاح في التحميل.",
    spw: 3, weeks: 8, minutes: 50, refs: [R.ptTka, R.aaosTka],
    devices: [
      ["exercise", "recommended", null, 35],
      ["electro", "recommended", "NMES للرباعية", 15, "موصى به (APTA TKA CPG)"],
      ["compression", "optional", null, 15, "للتورّم"],
      ["cpm", "not_recommended", null, null, "AAOS: لا يُنصح به روتينياً"],
    ],
  },
  {
    code: "tha-geriatric", titleAr: "ما بعد استبدال مفصل الورك الكلّي", titleEn: "Total Hip Arthroplasty (THA) Rehabilitation",
    category: "post_surgical", ageGroup: "geriatric",
    summary: "مشيٌ مبكّر، تقويةُ الألوية، والتزامٌ باحتياطات الخلع بحسب المدخل الجراحي.",
    goals: "مشيٌ مستقلّ بلا عرج، قوةُ الألوية، أمانٌ في الأنشطة اليومية.",
    assessment: "TUG، الجلوس والقيام ٣٠ ثانية، 6MWT، HOOS-JR، تحليلُ المشي.",
    exercises: "تمارينُ متساويةُ القياس مبكّراً، تقويةُ الألوية والفخذ، تدريبُ المشي والدرج والنقل، توازن.",
    contraindications: "علاماتُ خلعٍ أو عدوى أو جلطة — إحالةٌ فورية.",
    precautions: "احتياطاتُ الخلع بحسب المدخل (خلفيّ: لا انثناء > ٩٠° ولا تقريب ولا دوران داخلي) وتعليماتُ الجرّاح.",
    spw: 3, weeks: 8, minutes: 45, refs: [R.aaosHip],
    devices: [
      ["exercise", "recommended", null, 35],
      ["electro", "optional", "NMES للألوية والرباعية", 15, null],
      ["compression", "optional", null, 15, null],
    ],
  },
  {
    code: "rotator-cuff-repair-adult", titleAr: "ما بعد إصلاح الكفة المدوّرة", titleEn: "Rotator Cuff Repair Rehabilitation",
    category: "post_surgical", ageGroup: "adult",
    summary: "حمايةُ الإصلاح في الأسابيع الأولى ثم حركةٌ وتقويةٌ متدرّجة بحسب حجم التمزّق وتعليمات الجرّاح.",
    goals: "حمايةُ الوتر المُصلَح، استعادةُ الحركة ثم القوة، العودةُ للوظيفة.",
    assessment: "مدى الحركة السلبي والفعّال، الألم، ASES أو Constant، القوة (بعد ١٢ أسبوعاً).",
    exercises: "٠–٦ أسابيع: معلاقٌ وحركةٌ سلبية لطيفة؛ ٦–١٢: حركةٌ فعّالة مساعدة ثم فعّالة؛ بعد ١٢: تقويةٌ متدرّجة.",
    contraindications: "لا تقويةَ فعّالة قبل التئام الوتر بحسب الجرّاح.",
    precautions: "التمزّقاتُ الكبيرة تحتاج تدرّجاً أبطأ؛ تعليماتُ الجرّاح مقدَّمة.",
    spw: 2, weeks: 16, minutes: 45, refs: [R.aaosRc],
    devices: [
      ["exercise", "recommended", "مرحليٌّ بحسب الالتئام", 30],
      ["hot_pack", "optional", null, 15, null],
      ["electro", "optional", "TENS للألم", 15, null],
      ["cpm", "optional", null, 20, "لا فائدةَ إضافية ثابتة (AAOS)"],
    ],
  },
  {
    code: "distal-radius-fracture-adult", titleAr: "ما بعد كسر الكعبرة البعيد", titleEn: "Distal Radius Fracture — Post-immobilization",
    category: "post_surgical", ageGroup: "adult",
    summary: "بعد فكّ الجبس أو التثبيت الجراحي: استعادةُ حركة الرسغ والساعد وقوة القبضة.",
    goals: "استعادةُ حركة الرسغ والدوران، قوةُ القبضة، وظيفةُ اليد.",
    assessment: "PRWE، مدى الحركة، قوةُ القبضة، التورّم، علاماتُ متلازمة الألم الناحي المركّب (CRPS).",
    exercises: "تمارينُ مدى الحركة للرسغ والأصابع والساعد، تقويةٌ متدرّجة للقبضة، أنشطةٌ وظيفية.",
    contraindications: "عدمُ التئامٍ بحسب الأشعة.",
    precautions: "حركةُ الأصابع مبكّراً حتى أثناء الجبس؛ الانتباهُ لعلامات CRPS.",
    spw: 2, weeks: 8, minutes: 40, refs: [R.aaosDrf],
    devices: [
      ["exercise", "recommended", null, 25],
      ["wax", "optional", "شمعٌ قبل التمارين للتيبّس", 15, null],
      ["hot_pack", "optional", null, 15, null],
      ["compression", "optional", null, 15, "للتورّم"],
      ["ultrasound", "not_recommended", null, null, null],
    ],
  },

  // ═══ عصبية ═══
  {
    code: "stroke-subacute-adult", titleAr: "الجلطة الدماغية — المرحلة تحت الحادّة", titleEn: "Stroke — Subacute Rehabilitation (Hemiparesis)",
    category: "neurological", ageGroup: "adult",
    summary: "الأشهرُ الستّة الأولى نافذةُ التعافي الأكبر: تدريبٌ مكثّفٌ متكرّرٌ موجَّهٌ بالمهمّة.",
    goals: "المشيُ المستقلّ، استعمالُ الطرف العلوي، الاستقلاليةُ في الأنشطة اليومية، منعُ المضاعفات (الكتف، السقوط).",
    assessment: "Fugl-Meyer، Berg Balance، سرعةُ المشي 10MWT، 6MWT، FAC، Modified Ashworth للتشنّج، Barthel.",
    exercises: "تدريبٌ موجَّهٌ بالمهمّة (Task-oriented)، تدريبُ المشي المكثّف، توازن، تقوية، الحركةُ المقيّدة المحفّزة (CIMT) للذراع، تمطيطٌ ووضعية.",
    contraindications: "عدمُ استقرارٍ طبيّ (ضغطٌ أو قلب) — بعد إذن الطبيب.",
    precautions: "حمايةُ الكتف المصاب من الشدّ، الوقايةُ من السقوط، مراقبةُ الضغط.",
    spw: 5, weeks: 12, minutes: 60, refs: [R.ahaStroke, R.niceStroke, R.cochraneGait],
    devices: [
      ["exercise", "recommended", "تدريبٌ موجَّهٌ بالمهمّة ومشيٌ مكثّف", 45],
      ["robotik", "optional", "تدريبُ مشيٍ روبوتيّ مع العلاج التقليدي لغير القادر على المشي", 30, "Cochrane 2020: يزيد فرصةَ المشي المستقلّ لغير القادر على المشي في الأشهر الثلاثة الأولى — والإرشاداتُ تتفاوت في درجته"],
      ["electro", "recommended", "تحفيزٌ كهربائيٌّ وظيفيّ (FES/NMES) لرافعات القدم وللكتف المتدلّي", 20, "AHA: للقدم المتدلّية وخلع الكتف الجزئي"],
      ["shockwaves", "optional", "على العضلات المتشنّجة", 10, "للتشنّج — دليلٌ متوسّط"],
      ["needle", "optional", "على العضلات المتشنّجة", 10, DN + " — دليلٌ محدود"],
    ],
  },
  {
    code: "stroke-chronic-adult", titleAr: "الجلطة الدماغية — المرحلة المزمنة", titleEn: "Stroke — Chronic Phase (> 6 months)",
    category: "neurological", ageGroup: "adult",
    summary: "التحسّنُ ممكنٌ بعد ستّة أشهر بالتدريب المكثّف عالي الشدّة.",
    goals: "زيادةُ سرعة المشي ومسافته، تحسينُ اللياقة، الحفاظُ على الاستقلالية.",
    assessment: "10MWT، 6MWT، Berg، Fugl-Meyer، Modified Ashworth.",
    exercises: "تدريبُ مشيٍ متوسّط إلى عالي الشدّة (على السير وفوق الأرض)، تدريبٌ هوائيّ، تقوية، تمارينُ الذراع الموجّهة بالمهمّة.",
    contraindications: "عدمُ استقرارٍ قلبيّ — إذنُ الطبيب لتمارين الشدّة العالية.",
    precautions: "مراقبةُ النبض والضغط أثناء الشدّة العالية.",
    spw: 3, weeks: 12, minutes: 60, refs: [R.hornby, R.ahaStroke],
    devices: [
      ["exercise", "recommended", "مشيٌ عالي الشدّة + هوائيّ + تقوية", 45],
      ["robotik", "not_recommended", null, null, "ANPT: لا يُفضَّل على تدريب المشي العادي للقادر على المشي"],
      ["electro", "optional", "FES لرافعات القدم", 20, null],
      ["shockwaves", "optional", "على العضلات المتشنّجة", 10, null],
    ],
  },
  {
    code: "sci-incomplete-adult", titleAr: "إصابة الحبل الشوكي غير الكاملة", titleEn: "Incomplete Spinal Cord Injury",
    category: "neurological", ageGroup: "adult",
    summary: "استعادةُ المشي بقدر الإمكان، والوقايةُ من المضاعفات (القرح، التيبّس، هشاشة العظام).",
    goals: "تحسينُ المشي والتوازن والنقل، الاستقلالية، منعُ المضاعفات.",
    assessment: "تصنيفُ ASIA (AIS)، WISCI II، 10MWT، 6MWT، Berg، SCIM.",
    exercises: "تدريبُ المشي المكثّف (فوق الأرض وعلى السير)، تقوية، توازن، تدريبُ النقل والكرسي المتحرّك، تمطيط.",
    contraindications: "عدمُ ثبات العمود الفقري بعد الإصابة — إذنُ الجرّاح.",
    precautions: "خللُ التنظيم اللاإرادي (Autonomic dysreflexia) في الإصابات فوق T6، هبوطُ الضغط الانتصابي، العناية بالجلد.",
    spw: 3, weeks: 12, minutes: 60, refs: [R.hornby],
    devices: [
      ["exercise", "recommended", null, 45],
      ["robotik", "optional", "مشيٌ روبوتيّ لغير القادر على المشي فوق الأرض", 30, null],
      ["electro", "optional", "FES للدراجة أو للعضلات", 20, null],
    ],
  },
  {
    code: "parkinsons-geriatric", titleAr: "مرض باركنسون", titleEn: "Parkinson's Disease",
    category: "neurological", ageGroup: "geriatric",
    summary: "تمارينٌ منتظمة طوال المرض: مشيٌ بإشارات، توازن، تقوية، وتمارينٌ هوائية.",
    goals: "الحفاظُ على المشي والتوازن، منعُ السقوط، الحفاظُ على الاستقلالية.",
    assessment: "Hoehn & Yahr، MDS-UPDRS الجزء الثالث، Mini-BESTest، TUG، 10MWT، تجمّدُ المشي (FOG-Q).",
    exercises: "مشيٌ بإشاراتٍ سمعية أو بصرية (Cueing)، تمارينُ التوازن، تقوية، هوائيّ (سير/دراجة)، استراتيجياتُ الحركة، LSVT BIG.",
    contraindications: "هبوطُ الضغط الانتصابي الشديد — تعديلُ الوضعيات.",
    precautions: "التدريبُ في فترة عمل الدواء (On)، وخطرُ السقوط.",
    spw: 2, weeks: 12, minutes: 60, refs: [R.pd],
    devices: [
      ["exercise", "recommended", null, 50],
      ["robotik", "optional", "تدريبُ مشيٍ روبوتيّ", 30, "ليس أفضلَ من السير — للمتقدّم"],
    ],
  },
  {
    code: "multiple-sclerosis-adult", titleAr: "التصلّب اللويحي المتعدّد", titleEn: "Multiple Sclerosis",
    category: "neurological", ageGroup: "adult",
    summary: "تمارينٌ هوائية وتقوية وتوازن بحسب الإعياء، وإدارةُ التشنّج.",
    goals: "تحسينُ المشي والتوازن، خفضُ الإعياء، الحفاظُ على الاستقلالية.",
    assessment: "EDSS (من الطبيب)، 25-Foot Walk، 6MWT، Berg، MFIS للإعياء، Modified Ashworth.",
    exercises: "هوائيّ متوسّط، تقوية، توازن، تمطيطٌ للتشنّج، إدارةُ الطاقة (Energy conservation).",
    contraindications: "انتكاسةٌ حادّة (Relapse) — تخفيفٌ أو إيقاف.",
    precautions: "تجنّبُ الحرارة الزائدة (ظاهرة Uhthoff)، فالحرارةُ تزيد الأعراض مؤقّتاً.",
    spw: 2, weeks: 12, minutes: 50, refs: [R.niceMs],
    devices: [
      ["exercise", "recommended", null, 40],
      ["robotik", "optional", null, 30, null],
      ["electro", "optional", "FES لرافعات القدم", 20, null],
      ["hot_pack", "not_recommended", null, null, "الحرارةُ تزيد الأعراض (Uhthoff)"],
      ["infrared", "not_recommended", null, null, "الحرارةُ تزيد الأعراض"],
      ["wax", "not_recommended", null, null, "الحرارةُ تزيد الأعراض"],
    ],
  },
  {
    code: "bells-palsy-all", titleAr: "شلل العصب الوجهي (شلل بِل)", titleEn: "Bell's Palsy (Facial Nerve Palsy)",
    category: "neurological", ageGroup: "all",
    summary: "أغلبُ الحالات تتعافى تلقائياً؛ الدواءُ المبكّر من الطبيب، والعلاجُ الطبيعي لإعادة التدريب ومنع التزامُن الحركي (Synkinesis).",
    goals: "استعادةُ حركة الوجه المتناظرة، منعُ التزامن الحركي، حمايةُ العين.",
    assessment: "House-Brackmann، Sunnybrook Facial Grading System.",
    exercises: "إعادةُ تدريبٍ عصبيّ عضليّ للوجه أمام المرآة (Neuromuscular retraining)، حركاتٌ صغيرة دقيقة، تدليكٌ لطيف.",
    contraindications: "أعراضٌ عصبيةٌ أخرى أو بطءٌ شديد في التعافي — إحالةٌ للتقييم.",
    precautions: "حمايةُ العين من الجفاف، وتجنّبُ التمارين القوية الواسعة التي تزيد التزامن.",
    spw: 2, weeks: 8, minutes: 30, refs: [R.bells],
    devices: [
      ["exercise", "recommended", "إعادةُ تدريبٍ أمام المرآة", 20],
      ["electro", "not_recommended", null, null, "لا دليلَ كافٍ، وقد يزيد التزامنَ الحركي"],
      ["laser", "optional", null, 10, WEAK],
      ["infrared", "optional", null, 10, WEAK],
    ],
  },
  {
    code: "cerebral-palsy-pediatric", titleAr: "الشلل الدماغي عند الأطفال", titleEn: "Cerebral Palsy",
    category: "neurological", ageGroup: "pediatric",
    summary: "تدريبٌ موجَّهٌ بالهدف (Goal-directed) ومكثّف، مع إدارة التشنّج والوقاية من التشوّهات.",
    goals: "تحقيقُ أهدافٍ وظيفية يختارها الطفل والأسرة، تحسينُ المشي والجلوس والتوازن.",
    assessment: "GMFCS، GMFM-66، Modified Ashworth، مدى الحركة، أهدافُ GAS.",
    exercises: "تدريبٌ وظيفيٌّ موجَّهٌ بالهدف، CIMT أو تدريبٌ ثنائيّ للذراعين في الشلل النصفي، تقوية، تدريبُ المشي، برنامجٌ منزليّ مع الأسرة.",
    contraindications: "خلعُ الورك أو تشوّهاتٌ ثابتة — تقييمٌ عظميّ.",
    precautions: "مراقبةُ الورك بالأشعة بحسب GMFCS، وإشراكُ الأسرة.",
    spw: 3, weeks: 12, minutes: 45, refs: [R.cp],
    devices: [
      ["exercise", "recommended", null, 40],
      ["robotik", "optional", "تدريبُ مشيٍ روبوتيّ للأطفال (حسب المقاس)", 30, "دليلٌ متوسّط — يُضاف للتدريب لا يحلّ محلّه"],
      ["electro", "optional", "NMES / FES", 15, null],
      ["shockwaves", "optional", "على العضلات المتشنّجة", 10, null],
    ],
  },
  {
    code: "brachial-plexus-birth-pediatric", titleAr: "شلل الضفيرة العضدية الولادي (شلل إرب)", titleEn: "Brachial Plexus Birth Injury (Erb's Palsy)",
    category: "neurological", ageGroup: "pediatric",
    summary: "إصابةُ الضفيرة العضدية أثناء الولادة. الحفاظُ على مدى الحركة ومتابعةُ التعافي، والإحالةُ الجراحية إن لم يتحسّن.",
    goals: "منعُ تيبّس الكتف والكوع، تحفيزُ الحركة، دمجُ الذراع في اللعب والوظيفة.",
    assessment: "Active Movement Scale (AMS)، Mallet (للأكبر سنّاً)، مدى الحركة السلبي، متابعةُ عودة ثني الكوع بعمر ٣ أشهر.",
    exercises: "تمارينُ مدى حركةٍ لطيفة يومياً (خاصّةً الدوران الخارجي)، تحفيزٌ حسّيّ وحركيّ عبر اللعب، تدريبُ الأسرة.",
    contraindications: "كسرُ الترقوة أو العضد المرافق في الأسابيع الأولى — حذرٌ في الحركة.",
    precautions: "عدمُ عودة ثني الكوع بعمر ٣–٦ أشهر ⟵ إحالةٌ لجرّاح الأعصاب.",
    spw: 2, weeks: 12, minutes: 30, refs: [],
    devices: [
      ["exercise", "recommended", "مدى حركةٍ لطيف ولعبٌ وظيفيّ", 25],
      ["electro", "optional", "تحفيزٌ كهربائيّ للعضلات", 10, "دليلٌ محدود — يُقرّه الأخصائيّ"],
    ],
  },
  {
    code: "torticollis-cmt-pediatric", titleAr: "الصعر الخِلقي العضلي", titleEn: "Congenital Muscular Torticollis",
    category: "neurological", ageGroup: "pediatric",
    summary: "قِصَرُ العضلة القصّية الترقوية الخشّائية عند الرضيع. البدءُ قبل عمر ٣ أشهر يعطي أفضل النتائج.",
    goals: "مدى حركةٍ كامل للرقبة، استقامةُ الرأس، منعُ تفلطح الرأس (Plagiocephaly).",
    assessment: "مدى الدوران والميل الجانبي، Muscle Function Scale، درجةُ الشدّة، تفلطحُ الرأس، فحصُ الورك.",
    exercises: "تمطيطٌ لطيف يومياً، تقويةٌ نشطة للجهة المقابلة، وضعياتٌ وحملٌ صحيح، وقتٌ على البطن (Tummy time)، برنامجٌ منزليّ للأسرة.",
    contraindications: "صعرٌ غيرُ عضليّ (عظميّ، عصبيّ، بصريّ) — إحالة.",
    precautions: "تمطيطٌ لطيفٌ بلا ألم؛ لا شدَّ قسرياً.",
    spw: 1, weeks: 12, minutes: 30, refs: [R.cmt],
    devices: [
      ["exercise", "recommended", "تمطيطٌ لطيف + تقوية + وضعيات", 25],
    ],
  },

  // ═══ البتر والأطراف ═══
  {
    code: "lower-limb-preprosthetic-adult", titleAr: "ما قبل تركيب الطرف السفلي", titleEn: "Lower Limb Amputation — Pre-prosthetic Rehabilitation",
    category: "amputation", ageGroup: "adult",
    summary: "تجهيزُ الجذع والجسم للطرف: شكلُ الجذع، القوة، منعُ التقفّع، والاستقلاليةُ في النقل.",
    goals: "جذعٌ مخروطيّ مستعدٌّ للقالب، منعُ تقفّع الورك والركبة، قوةُ الطرفين، الاستقلاليةُ في النقل والكرسي.",
    assessment: "محيطُ الجذع وشكلُه، الجرح، مدى حركة الورك والركبة، قوةُ العضلات، التوازنُ على ساقٍ واحدة، AMPPRO، ألمُ الطرف الشبحيّ.",
    exercises: "تضميدٌ مرن (Shrinker)، وضعياتٌ ضدّ التقفّع (الاستلقاء على البطن)، تقويةُ باسطات ومبعدات الورك، تمارينُ الجذع، توازن، نقل.",
    contraindications: "جرحٌ غيرُ ملتئم أو عدوى — لا تحميلَ على الجذع.",
    precautions: "الجذعُ الوعائي (السكّري) يلتئم ببطء؛ فحصُ الطرف السليم يومياً.",
    spw: 3, weeks: 6, minutes: 45, refs: [R.vaLla],
    devices: [
      ["exercise", "recommended", "تقويةُ الورك والجذع + توازن + نقل", 35],
      ["compression", "optional", "ضغطٌ لتشكيل الجذع وتخفيف الوذمة", 15, "مع الـ Shrinker لا بديلاً عنه"],
      ["electro", "optional", "TENS لألم الطرف الشبحي", 15, WEAK],
      ["laser", "optional", "لتسريع التئام الجرح", 10, WEAK],
    ],
  },
  {
    code: "lower-limb-prosthetic-gait-adult", titleAr: "التدريب على المشي بالطرف السفلي", titleEn: "Lower Limb Prosthetic Gait Training",
    category: "amputation", ageGroup: "adult",
    summary: "من لبس الطرف وتحميل الوزن إلى مشيٍ متناظرٍ مستقلّ على الأسطح والدرج.",
    goals: "مشيٌ مستقلٌّ متناظر، لبسٌ وخلعٌ صحيح، مستوى K المستهدف، العودةُ للعمل.",
    assessment: "AMPPRO، 2MWT أو 6MWT، TUG، تحليلُ المشي، ملاءمةُ القالب، Houghton، مستوى K.",
    exercises: "تحميلُ الوزن على الطرف، توازنٌ بين القضبان، تدريبُ الخطوة ومراحل المشي، الأسطحُ المختلفة والدرج والمنحدر، النهوضُ من السقوط.",
    contraindications: "قرحةٌ أو احمرارٌ مستمرّ على الجذع — تعديلُ القالب قبل المتابعة.",
    precautions: "فحصُ الجذع قبل وبعد كلّ جلسة، وتعديلُ الجوارب (Socks) بحسب تغيّر الحجم.",
    spw: 3, weeks: 8, minutes: 60, refs: [R.vaLla],
    devices: [
      ["exercise", "recommended", "تدريبُ مشيٍ وتوازن", 50],
      ["robotik", "optional", "تدريبُ مشيٍ روبوتيّ في المراحل الأولى", 30, "دليلٌ محدود للمبتورين"],
    ],
  },
  {
    code: "upper-limb-amputation-adult", titleAr: "تأهيل بتر الطرف العلوي", titleEn: "Upper Limb Amputation Rehabilitation",
    category: "amputation", ageGroup: "adult",
    summary: "تجهيزُ الجذع، تدريبُ إشارات العضلات (Myo-training) للأطراف الذكية، ثم التدريبُ الوظيفيّ.",
    goals: "جذعٌ جاهز، إشاراتٌ عضليةٌ منفصلة للتحكّم، استعمالُ الطرف في الأنشطة اليومية.",
    assessment: "مدى الحركة والقوة، الجذع، اختبارُ الإشارات العضلية (EMG site testing)، ألمُ الطرف الشبحي، AM-ULA أو SHAP.",
    exercises: "تضميدٌ وتشكيل، مدى حركةٍ للكتف والكوع، تقوية، تدريبُ الإشارات العضلية بالبرنامج، تدريبُ القبض والإفلات، أنشطةٌ يومية ثنائية.",
    contraindications: "جرحٌ غيرُ ملتئم.",
    precautions: "الاستعمالُ المفرط للطرف السليم (Overuse) — تثقيفٌ ووقاية.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.vaUla],
    devices: [
      ["exercise", "recommended", "مدى حركة + تقوية + تدريبٌ وظيفيّ", 35],
      ["electro", "optional", "TENS لألم الطرف الشبحي", 15, WEAK],
    ],
  },

  // ═══ روماتيزمية ومزمنة ═══
  {
    code: "rheumatoid-arthritis-adult", titleAr: "التهاب المفاصل الروماتويدي", titleEn: "Rheumatoid Arthritis",
    category: "rheumatologic", ageGroup: "adult",
    summary: "التمارينُ المنتظمة آمنةٌ ومفيدة؛ الشدّةُ تُضبط بحسب نشاط المرض.",
    goals: "تخفيفُ الألم والتيبّس، الحفاظُ على القوة والحركة، حمايةُ المفاصل.",
    assessment: "DAS28 (من الطبيب)، HAQ، قوةُ القبضة، مدى الحركة، عددُ المفاصل المتورّمة.",
    exercises: "هوائيٌّ متوسّط، تقوية، مدى حركة، تمارينُ اليد، حمايةُ المفاصل، إدارةُ الطاقة.",
    contraindications: "مفصلٌ ملتهبٌ حادّ — راحةٌ نسبية له وحركةٌ لطيفة؛ عدمُ ثبات الفقرات العنقية العلوية (C1–C2).",
    precautions: "تجنّبُ الأحمال العالية على المفاصل الملتهبة؛ الحرارةُ للتيبّس لا للمفصل الملتهب.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.acrRa, R.eularPa],
    devices: [
      ["exercise", "recommended", null, 35],
      ["wax", "optional", "شمعٌ لليدين في المرحلة غير النشطة", 15, null],
      ["hot_pack", "optional", null, 15, "لا على المفصل الملتهب"],
      ["laser", "optional", null, 10, WEAK],
      ["electro", "optional", "TENS", 15, WEAK],
    ],
  },
  {
    code: "axial-spa-adult", titleAr: "التهاب الفقار اللاصق / التهاب الفقار المحوري", titleEn: "Axial Spondyloarthritis (Ankylosing Spondylitis)",
    category: "rheumatologic", ageGroup: "adult",
    summary: "التمارينُ المنتظمة مدى الحياة جزءٌ أساسيٌّ من العلاج مع الدواء.",
    goals: "الحفاظُ على حركة العمود الفقري والصدر والوضعية، تخفيفُ الألم والتيبّس.",
    assessment: "BASFI، BASDAI، BASMI، اتّساعُ الصدر، مسافةُ الجدار-القذال (Occiput-to-wall).",
    exercises: "تمارينُ الحركة والبسط للعمود الفقري، تمارينُ التنفّس، تقويةُ الجذع، هوائيّ، سباحة.",
    contraindications: "كسرٌ في العمود المتيبّس بعد سقوطٍ ولو بسيط — إحالةٌ عاجلة.",
    precautions: "لا تحريكَ عاليَ السرعة (Manipulation) للعمود المتيبّس.",
    spw: 2, weeks: 8, minutes: 45, refs: [R.asas],
    devices: [
      ["exercise", "recommended", null, 35],
      ["hot_pack", "optional", null, 15, null],
      ["infrared", "optional", null, 10, null],
      ["traction", "not_recommended", null, null, null],
    ],
  },
  {
    code: "fibromyalgia-adult", titleAr: "الألم العضلي الليفي", titleEn: "Fibromyalgia",
    category: "rheumatologic", ageGroup: "adult",
    summary: "التمارينُ هي التوصيةُ القوية الوحيدة في EULAR؛ تبدأ منخفضةً وتزيد ببطء.",
    goals: "تخفيفُ الألم والإعياء، تحسينُ النوم والوظيفة، الإدارةُ الذاتية.",
    assessment: "FIQR، NPRS، مقياسُ الإعياء، 6MWT.",
    exercises: "هوائيٌّ منخفضُ الشدّة متدرّج، تقويةٌ خفيفة، تمارينُ مائية، Tai chi أو Yoga، تثقيفٌ بعلم الألم.",
    contraindications: "—",
    precautions: "الزيادةُ البطيئة جداً تمنع الانتكاسة بعد التمارين.",
    spw: 2, weeks: 12, minutes: 45, refs: [R.eularFm],
    devices: [
      ["exercise", "recommended", "هوائيٌّ متدرّج + تقويةٌ خفيفة", 35],
      ["hot_pack", "optional", null, 15, "توصيةٌ ضعيفة (EULAR: العلاجُ الحراري المائي)"],
      ["electro", "optional", "TENS", 15, WEAK],
      ["needle", "optional", null, 10, DN + " — دليلٌ ضعيف"],
      ["laser", "not_recommended", null, null, null],
    ],
  },
  {
    code: "osteoporosis-falls-geriatric", titleAr: "هشاشة العظام والوقاية من السقوط", titleEn: "Osteoporosis & Falls Prevention",
    category: "rheumatologic", ageGroup: "geriatric",
    summary: "تمارينُ التوازن والتقوية تقلّل السقوطَ والكسور؛ أساسُ الوقاية عند كبار السنّ.",
    goals: "خفضُ خطر السقوط، تقويةُ العضلات والعظام، تحسينُ التوازن والثقة.",
    assessment: "TUG، Berg، الجلوس والقيام ٣٠ ثانية، سرعةُ المشي، تاريخُ السقوط، FES-I للخوف من السقوط.",
    exercises: "تمارينُ التوازن المتدرّجة (Otago)، تقويةٌ مقاومةٌ تدريجية، تمارينُ تحميل الوزن، Tai chi، وضعيةٌ وتمارينُ بسط الظهر.",
    contraindications: "كسرٌ انضغاطيٌّ حادّ في فقرة — تقييمٌ أوّلاً.",
    precautions: "تجنّبُ الانثناء القويّ للعمود مع الدوران (يزيد خطر كسر الفقرات).",
    spw: 2, weeks: 12, minutes: 45, refs: [R.falls],
    devices: [
      ["exercise", "recommended", "توازن (Otago) + تقوية", 40],
      ["megnatik", "not_recommended", null, null, "لا دليلَ على زيادة كثافة العظم"],
    ],
  },
  {
    code: "jia-pediatric", titleAr: "التهاب المفاصل اليفعي مجهول السبب", titleEn: "Juvenile Idiopathic Arthritis",
    category: "rheumatologic", ageGroup: "pediatric",
    summary: "الحفاظُ على الحركة والقوة والمشاركة في اللعب والمدرسة مع العلاج الدوائي.",
    goals: "منعُ التقفّع، الحفاظُ على القوة واللياقة، المشاركةُ في الأنشطة.",
    assessment: "CHAQ، مدى الحركة للمفاصل المصابة، القوة، المشي.",
    exercises: "مدى حركة، تقوية، هوائيّ، تمارينُ مائية، جبائرُ ليلية عند الحاجة، لعبٌ ورياضةٌ مناسبة.",
    contraindications: "مفصلٌ ملتهبٌ حادّ — حركةٌ لطيفة لا تحميل.",
    precautions: "صفائحُ النموّ المفتوحة — لا موجاتٍ صادمة ولا شدّةٍ زائدة.",
    spw: 2, weeks: 8, minutes: 40, refs: [R.acrJia],
    devices: [
      ["exercise", "recommended", null, 30],
      ["wax", "optional", null, 15, null],
      ["hot_pack", "optional", null, 15, null],
      ["shockwaves", "not_recommended", null, null, "صفائحُ النموّ"],
    ],
  },

  // ═══ أخرى ═══
  {
    code: "lymphedema-adult", titleAr: "الوذمة اللمفية", titleEn: "Lymphedema (e.g. post-mastectomy)",
    category: "other", ageGroup: "adult",
    summary: "العلاجُ المزيل للاحتقان المركّب (CDT): تصريفٌ لمفيٌّ يدويّ، ضمادٌ متعدّد الطبقات، تمارين، عنايةٌ بالجلد.",
    goals: "تقليلُ حجم الطرف، الحفاظُ عليه بالملبس الضاغط، منعُ العدوى.",
    assessment: "محيطُ الطرف أو حجمُه، مرحلةُ ISL، فحصُ الجلد، Stemmer sign، الوظيفة (DASH).",
    exercises: "تصريفٌ لمفيٌّ يدويّ (MLD)، ضمادٌ متعدّد الطبقات، تمارينُ مع الضماد، تقويةٌ متدرّجة، ملبسٌ ضاغط للصيانة.",
    contraindications: "عدوى حادّة (Cellulitis)، جلطةٌ وريدية حادّة، قصورٌ قلبيٌّ غير مضبوط — لا ضغطَ ولا تصريف.",
    precautions: "الحرارةُ ممنوعة على الطرف؛ وسرطانٌ نشطٌ غيرُ معالَج — بإذن الطبيب.",
    spw: 3, weeks: 4, minutes: 60, refs: [R.isl],
    devices: [
      ["exercise", "recommended", null, 20],
      ["compression", "optional", "ضغطٌ هوائيٌّ متقطّع (IPC) بضغطٍ منخفض", 30, "مساعدٌ ضمن CDT لا بديلٌ عنه"],
      ["laser", "optional", "ليزرٌ منخفضُ الشدّة", 15, "دليلٌ متوسّط بعد استئصال الثدي"],
      ["hot_pack", "not_recommended", null, null, "الحرارةُ تزيد الوذمة"],
      ["infrared", "not_recommended", null, null, "الحرارةُ تزيد الوذمة"],
      ["wax", "not_recommended", null, null, "الحرارةُ تزيد الوذمة"],
    ],
  },
];

// ── بناءُ SQL ─────────────────────────────────────────────────────────────────
const lit = (v: string | null | undefined) => (v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const num = (v: number | null | undefined) => (v === null || v === undefined ? "NULL" : String(Math.trunc(v)));

function protocolSql(p: Seed): string {
  const refs = p.refs.map((r) => ({ title: r.title, org: r.org, year: r.year, url: r.url ?? null }));
  const deviceRows = p.devices.map(([code, ev, params, minutes, note], i) =>
    `(${lit(code)}, ${lit(ev)}, ${lit(params ?? null)}::text, ${num(minutes ?? null)}::int, ${lit(note ?? null)}::text, ${i})`).join(",\n    ");
  const insertProtocol = `INSERT INTO physio_protocols
    (code, title_ar, title_en, category, age_group, summary, goals, assessment, exercises, contraindications, precautions,
     sessions_per_week, duration_weeks, session_minutes, "references", status, created_by_name, updated_by_name)
  VALUES (${lit(p.code)}, ${lit(p.titleAr)}, ${lit(p.titleEn)}, ${lit(p.category)}, ${lit(p.ageGroup)}, ${lit(p.summary)}, ${lit(p.goals)},
     ${lit(p.assessment)}, ${lit(p.exercises)}, ${lit(p.contraindications)}, ${lit(p.precautions)},
     ${num(p.spw)}, ${num(p.weeks)}, ${num(p.minutes)}, ${lit(JSON.stringify(refs))}::jsonb, 'draft', 'زرعٌ أوّلي', 'زرعٌ أوّلي')
  ON CONFLICT (code) DO NOTHING
  RETURNING id`;
  if (!p.devices.length) return `${insertProtocol};`;
  return `WITH p AS (
  ${insertProtocol}
)
INSERT INTO physio_protocol_devices (protocol_id, device_id, evidence, parameters, minutes, note, display_order)
SELECT p.id, d.id, v.evidence, v.parameters, v.minutes, v.note, v.ord
FROM p
CROSS JOIN (VALUES
    ${deviceRows}
  ) AS v(code, evidence, parameters, minutes, note, ord)
JOIN devices d ON d.code = v.code;`;
}

export const name = "107_physio_protocol_seed";
export const sql = SEED.map(protocolSql).join("\n\n");
